version: '3.7'
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    depends_on:
      - postgres
      - redis
    ports:
      - 4000:4000
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d/
  redis:
    image: redis:6-alpine
    command: redis-server --appendonly yes
    volumes:
      - type: volume
        source: redis
        target: /data
        volume:
          nocopy: true
volumes:
  postgres:
  redis:
