version: '3.7'
services:
  app:
    build:
      target: prod
    restart: always
  nginx:
    restart: always
    volumes:
      - type: bind
        source: ./config/nginx/nginx.prod.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - certbot
  postgres:
    restart: always
  redis:
    restart: always
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
